modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="arsenic"
version="0.1.0"
displayName="Arsenic"
authors="ANError"
description='''
This is a mod that will cause your Minecraft to crash
'''
[[dependencies.arsenic]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.arsenic]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21.1)"
ordering="NONE"
side="BOTH"
